### ISSUE TITLE
Allow a loading directory for JS libraries out of the gem

### ISSUE THREAD

**Issue by fgi** [manastech/middleman-search#17]
Currently, lunr JS library is loaded in gem's directory `vendor/assets/javascripts/` (load made in `search-index-resource.rb`file).
So an update of the gem is needed to update third party libraries (lunr,  i18n, ...).
Lunr version is 0.7.1 now.

Would it be possible to search for JS libs in another location, for example `source/javascripts` in the middleman project, and load from `vendor/assets/javascripts/` in none is found?
Then users could put new libs versions in their project, and rollback to gem libs if they have an issue.

This is just a suggestion. It may not be suitable if you want to keep a close dependency relationship between middleman-search and lunr versions.
And I don't know if there is an impact on the assets pipeline (I'm not using it).

Thanks

**Comment by matiasgarciaisaia** [comment]
Thanks for the issues (this, and #16!).

We hope to have fixed this - we'll be releasing a new version of the gem during the afternoon 👍

**Comment by fgi** [comment]
Both evolutions work well. :+1: 
Many thanks!
And congratulations to you guys at Manas for the great things you do with Ruby and Crystal!
