### ISSUE TITLE
middleman 4.0 support

### ISSUE THREAD

**Issue by JohannaE** [manastech/middleman-search#6]
hello,

does this exentsion support middleman 4.0. I got the following error message:

```
middleman-search was resolved to 0.0.1, which depends on
  middleman-core (~> 3.2)
```

and the middleman server crashed with the following error message:

```
== The Middleman is loading
/home/xx/.gem/ruby/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/extensions.rb:86:in `load': Unknown Extension: search. Check the name and make sure you have referenced the extension's gem in your Gemfile. (RuntimeError)
```

**Comment by spalladino** [comment]
Hello @JohannaE! We have developed and tested this extension with Middleman 3 only I'm afraid. You're welcome to send a PR with the required changes to support both versions though; I don't expect it to be too difficult.
